logging:
  level:
    root: INFO
    se.salt.lobby: DEBUG

aws:
  credentials:
    access-key: test
    secret-key: test

  dynamodb:
    endpoint: http://localstack:4566

  sqs:
    endpoint: http://localstack:4566
    queue-url: http://localstack:4566/000000000000/session-created-queue