logging:
  level:
    root: WARN
    se.salt.lobby: INFO

aws:
  dynamodb:
    endpoint: ""
  sqs:
    queue-url: ${SQS_QUEUE_URL:https://sqs.eu-north-1.amazonaws.com/326803123265/session-created-queue}