logging:
  level:
    root: INFO
    se.salt.lobby: DEBUG

cors:
  allowAll: true

aws:
  region: eu-north-1
  dynamodb:
    endpoint: http://localhost:4566
  sqs:
    endpoint: http://localhost:4566
    queue-url: http://localhost:4566/000000000000/session-created-queue