logging:
  level:
    root: WARN
    se.salt.lobby: INFO

cors:
  allowAll: false
  allowedOrigins:
    - https://frontend-alb-1896419215.eu-north-1.elb.amazonaws.com
    - http://frontend-alb-1896419215.eu-north-1.elb.amazonaws.com

aws:
  region: eu-north-1
  dynamodb:
    endpoint: ""
  sqs:
    queue-url: ${SQS_QUEUE_URL:https://sqs.eu-north-1.amazonaws.com/326803123265/session-created-queue}